PersonalWebsite/Models/Article.cs
namespace PersonalWebsite.Models
{
    public class Article
    {
        public int ArticleId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    }
}

PersonalWebsite/Models/ErrorViewModel.cs
namespace PersonalWebsite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PersonalWebsite/Models/KeyKioskViewModel.cs
namespace PersonalWebsite.Models
{
    public class KeyKioskViewModel
    {
        public string Message { get; set; } = "Please enter 8 digit ID.";
        public string EnteredId { get; set; } = "";
    }
}

PersonalWebsite/Models/PageVisitStats.cs
namespace PersonalWebsite.Models
{
    public class PageVisitStats
    {
        public string URL { get; set; }
        public int VisitsEver { get; set; }
        public int VisitsYear { get; set; }
        public int VisitsMonth { get; set; }

        public PageVisitStats() { }

        public PageVisitStats(string url, int visitsEver, int visitsYear, int visitsMonth)
        {
            URL = url;
            VisitsEver = visitsEver;
            VisitsYear = visitsYear;
            VisitsMonth = visitsMonth;
        }
    }
}

PersonalWebsite/Models/Story.cs
namespace PersonalWebsite.Models
{
    public class Story
    {
        public int StoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public DateTime DateWritten { get; set; }
    }
}

PersonalWebsite/Models/VisitLog.cs
namespace PersonalWebsite.Models
{
    public class VisitLog
    {
        public int VisitLogId { get; set; }
        public string URL { get; set; }
        public DateTime Time { get; set; }

        public VisitLog() { }

        public VisitLog(string url, DateTime time)
        {
            URL = url;
            Time = time;
        }
    }
}

PersonalWebsite/Models/World.cs
namespace PersonalWebsite.Models
{
    public class World
    {
        public int WorldId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Identifier { get; set; }
    }
}

PersonalWebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Models;
using System.Diagnostics;

namespace PersonalWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly StatsDBContext _statsDb;

        public HomeController(ILogger<HomeController> logger, StatsDBContext statsDb)
        {
            _logger = logger;
            _statsDb = statsDb;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Game()
        {
            return View();
        }

        public IActionResult Randomizers()
        {
            return View();
        }

        public IActionResult Other()
        {
            return View();
        }

        public IActionResult Stats()
        {
            List<VisitLog> logs = _statsDb.VisitLogs.ToList();
            var pageVisits = logs.GroupBy(x => x.URL);
            List<PageVisitStats> stats = new List<PageVisitStats>();
            foreach (var visits in pageVisits)
            {
                int visitsEver = visits.Count();
                int visitsYear = visits.Where(x => x.Time >= DateTime.Now.AddYears(-1)).Count();
                int visitsMonth = visits.Where(x => x.Time >= DateTime.Now.AddMonths(-1)).Count();
                stats.Add(new PageVisitStats(visits.First().URL, visitsEver, visitsYear, visitsMonth));
            }
            return View(stats);
        }
    }
}

PersonalWebsite/Controllers/StoriesController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Models;
using System.Diagnostics;

namespace PersonalWebsite.Controllers
{
    public class StoriesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DBContext _db;

        public StoriesController(ILogger<HomeController> logger, DBContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            List<Story> stories = _db.Stories.OrderByDescending(x => x.DateWritten).ToList();
            return View(stories);
        }

        public IActionResult ReadStory(int storyId)
        {
            Story? story = _db.Stories.FirstOrDefault(x => x.StoryId == storyId);
            if (story == null)
            {
                return View(new Story());
            }
            else
            {
                string content = story.Content;
                //Add a tab before the first paragraph
                story.Content = "&emsp;" + story.Content;
                //Add break and tab in the paragraph breaks
                story.Content = story.Content.Replace("\r\n\r\n", "<br />&emsp;");
                return View(story);
            }
        }
    }
}

PersonalWebsite/Controllers/TabletopController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Models;
using System.Diagnostics;

namespace PersonalWebsite.Controllers
{
    public class TabletopController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly StatsDBContext _statsDb;

        public TabletopController(ILogger<HomeController> logger, StatsDBContext statsDb)
        {
            _logger = logger;
            _statsDb = statsDb;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult KeyKiosk()
        {
            KeyKioskViewModel model = new KeyKioskViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult KeyKiosk(KeyKioskViewModel model)
        {
            Dictionary<string, string> mapping = new Dictionary<string, string>()
            {
                { "57561732", "TLYM" },
                { "41722758", "ZMBJ" },
                { "21673881", "ZETU" },
                { "91892328", "NXMI" },
                { "48547175", "FJLR" },
                { "19444234", "NIZW" },
            };
            if (!string.IsNullOrEmpty(model.EnteredId) && mapping.ContainsKey(model.EnteredId))
            {
                model.Message = "Encrypted location: " + mapping[model.EnteredId];
            }
            else
            {
                model.Message = "Invalid ID.";
            }
            return View(model);
        }
    }
}

PersonalWebsite/Controllers/WorldbuildingController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.Models;
using System.Diagnostics;

namespace PersonalWebsite.Controllers
{
    public class WorldbuildingController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DBContext _db;

        public WorldbuildingController(ILogger<HomeController> logger, DBContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            List<World> world = _db.Worlds.ToList();
            return View(world);
        }

        public IActionResult Sabora()
        {
            return View();
        }

        public IActionResult Jetsetter()
        {
            List<Article> articles = _db.Articles.ToList();
            return View(articles);
        }

        public IActionResult ReadArticle(int articleId)
        {
            Article? article = _db.Articles.FirstOrDefault(x => x.ArticleId == articleId);
            if (article == null)
            {
                return View(new Article());
            }
            else
            {
                string content = article.Content;
                //Add a tab before the first paragraph
                article.Content = "&emsp;" + article.Content;
                //Add break and tab in the paragraph breaks
                article.Content = article.Content.Replace("\r\n", "<br />&emsp;");
                return View(article);
            }
        }
    }
}

PersonalWebsite/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Caleb Johnson's Personal Website";
}

<div class="text-center">
    <h3><a href="https://github.com/cjohnson57">Github</a></h3>
    <h3><a href="https://www.linkedin.com/in/caleb-johnson-3286b5141/">Linkedin</a></h3>
    <h3><a href="https://literateaxolotl.com/">Game Dev Website</a></h3>
    <h3><a href="https://www.youtube.com/channel/UCdv1oxIkPzxEto8oZj4AI5Q">Game Dev Youtube</a></h3>
    <h3><a href="https://bsky.app/profile/literateaxolotl.com">Game Dev Bluesky</a></h3>
    <h3>Email: c.johnson.57@outlook.com</h3>
</div>
<div>
    <p>Note about my email: This is an old spam email I check maybe once a week. I don't want to put my newer email on this site publicly, because I don't want it to also become a spam email.</p>
</div>

PersonalWebsite/Views/Home/Game.cshtml
@{
    ViewData["Title"] = "Game Dev";
}

<div class="text-center">
    <h3><a href="https://literateaxolotl.com/">Game Dev Website</a></h3>
    <h3><a href="https://www.youtube.com/channel/UCdv1oxIkPzxEto8oZj4AI5Q">Game Dev Youtube</a></h3>
    <h3><a href="https://bsky.app/profile/literateaxolotl.com">Game Dev Bluesky</a></h3>
</div>

<br />

<div>
    <p>
        I'm currently developing a game called Geneti-risks with my girlfriend. Geneti-risks is a hand-drawn, momentum-based platformer where you control a genetic experiment as you try to figure out what sent all the other experiments in your lab going crazy.
        This video is quite old at this point, but it gives you a general idea of what the game looks like. Obviously, graphics are nowhere near final, and physics have been adjusted since then:
    </p>
</div>

<div class="text-center">
    <iframe width="1120" height="630" src="https://www.youtube.com/embed/yHzPWPEmz8I?si=xiPSljUuJd8EmZ4V" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>

<div>
    <p>
        More frequent updates can be found on our Bluesky.
        To give a vague idea of who does what on the game: I do programming and level design, my girlfriend does art, and we collaboratively do story and characters.
    </p>
</div>

PersonalWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Caleb Johnson's Personal Website";
}

<div class="text-center">
    <h3>Welcome to my site. Here I consolidate information about various things I work on.</h3>    
</div>
<div>
    <p>I'm a <a asp-controller="Home" asp-action="Other">programmer</a> who also dabbles in writing. My primary off-work activity, currently, is <a asp-controller="Home" asp-action="Game">developing a game.</a> I'm also a maintainer for the <a href="https://ootrandomizer.com/">Ocarina of Time Randomizer</a>, and have worked on <a asp-controller="Home" asp-action="Randomizers">other randomizers</a> in the past.</p>
    <p>I enjoy <a asp-controller="Worldbuilding" asp-action="Index">worldbuilding</a>, though I'm no expert at it, and definitely end up hand-waving some things rather than thinking too hard about realistic geopolitics and sociology (though I wish I knew enough to be able to do so).</p>
    <p>I've written a book, which I'd like to publish one day, but it'll need more work first. In the meantime, I'm going to try writing <a asp-controller="Stories" asp-action="Index">more short stories.</a></p>
    <p>I grew up in Louisiana, and got my Bachelor's and Master's in computer engineering from Louisiana State University. My <a href="https://ieeexplore.ieee.org/document/9387363">Master's thesis</a> was a paper on algorithms used for randomizers. I currently live in the greater Los Angeles area.</p>
    <p>In my free time, I have a variety of interests:</p>
    <ul>
        <li>Video Games, especially ones made by Nintendo</li>
        <li>Board Games, especially Spirit Island</li>
        <li>Tabletop RPGs, with DnD being my most played by far, but I've tried at least a dozen systems at this point</li>
        <li>Books, usually fantasy or sci-fi</li>
        <li>Movies</li>
        <li>TV Series, especially animated ones</li>
        <li>Theme Parks</li>
        <li>Swimming</li>
    </ul>
</div>

PersonalWebsite/Views/Home/Other.cshtml
@{
    ViewData["Title"] = "Programming";
}

<div class="text-center">
    <h3><a href="https://github.com/cjohnson57">Github</a></h3>
    <h3><a href="https://www.linkedin.com/in/caleb-johnson-3286b5141/">Linkedin</a></h3>
</div>

<br />

<div>
    <p>
        For my job, I primarily develop ASP.NET web applications <a href="https://github.com/cjohnson57/PersonalWebsite">(like this one)</a>, which I have been doing for over 8 years.
        The sites I develop typically use an Entity Framework connection to a SQL database, which is used to make the site highly customizable so that most regular changes to the site can be made by the clients.
    </p>
    <p>
        I'm also highly proficient in python, having been one of the primary python developers on my senior design project, and writing python notebooks in Databricks for a previous job.
    </p>
    <p>
        I have some experience in machine learning. My senior project involved renting computation time to train ML models. I also used ML models in python/databricks at a previous job for text processing.
    </p>
    <p>
        Some other skills that I enjoy using, but haven't got a chance to since college: Writing verilog, programming microcontrollers/FPGAs, programming GPUs, and writing assembly (except occasionally for game hacking).
    </p>
</div>

PersonalWebsite/Views/Home/Randomizers.cshtml
@{
    ViewData["Title"] = "Randomizers";
}

<div>
    <h3><a href="https://ieeexplore.ieee.org/document/9387363">My Master's Thesis</a></h3>
    <p>
        When I first discovered randomizers, I was very interested in how their logic and item placement worked. TestRunner, one of the OG devs of OoT Randomizer and tech lead for Games Done Quick, helped me out and gave me a lot of info.
        However, I found that most of this info wasn't formally defined or even published anywhere. Since I felt like I was making no progress on my current thesis topic, I convinced my advisor to let me switch to this.
        In this paper, I give an overview of what a randomizer is, go over the 3 main algorithms for item placement in randomizers, and compare each of their pros and cons.
    </p>
    <h3><a href="https://ootrandomizer.com/">Ocarina of Time Randomizer</a></h3>
    <p>
        The first randomizer I discovered, after wanting to try it when seeing an Achievement Hunter let's play of it.
        For a while I only made small contributions, but eventually became one of the primary maintainers of the project, approving and merging PRs from others.
        I've developed several major features including key rings, custom player models, and custom music on the website version of the app.
    </p>
    <h3><a href="https://github.com/gamestabled/OoT3D_Randomizer">Ocarina of Time 3D Randomizer</a></h3>
    <p>
        When the randomizer for the 3DS version of Ocarina of Time came out, I noticed that the fill algorithm needed some fixing up. 
        After doing so, I continued working on it for a long while, making many fixes developing several major features. These include key rings, shopsanity, and an all locations reachable toggle.
    </p>
    <h3><a href="https://dk64randomizer.com/">Donkey Kong 64 Randomizer</a></h3>
    <p>
        I was lamenting that DK64 didn't have a randomizer, when I learned that there was one under development. I knew I had to get in on it.
        Despite only working on it for a short time, this is my most major contribution to a randomizer. I wrote the initial logic files, and wrote the system for parsing those files, placing items, and randomizing entrances from scratch.
        I didn't do too much after the initial development, but I loved getting to put my ideas of how a randomizer should be put together into action.
    </p>
</div>

PersonalWebsite/Views/Home/Stats.cshtml
@{
    ViewData["Title"] = "Site Stats";
}
@model List<PageVisitStats>

<table id="pageVisitsTable" class="display">
    <thead>
        <tr>
            <th>Page</th>
            <th>Visits Ever</th>
            <th>Visits in the Last Year</th>
            <th>Visits in the Last Month</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var stat in Model)
        {
            <tr>
                <td>@stat.URL</td>
                <td>@stat.VisitsEver</td>
                <td>@stat.VisitsYear</td>
                <td>@stat.VisitsMonth</td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#pageVisitsTable').DataTable({
            order: [[1, 'desc']], //Sort by VisitsEver, descending
            responsive: true,
        });
    });
</script>

PersonalWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonalWebsite.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/monkey2.ico">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.3/css/responsive.dataTables.min.css" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js" defer></script>
    <script src="https://cdn.datatables.net/responsive/3.0.3/js/dataTables.responsive.min.js" defer></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand text-light hide-not-mobile" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-navitems">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Game">Game Dev</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Randomizers">Randomizers</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Other">Other Programming</a>
                        </li>
                        <li class="nav-item hide-mobile nav-home">
                            <a class="nav-link text-light navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Stories" asp-action="Index">Short Stories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Worldbuilding" asp-action="Index">Worldbuilding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Stats">Site Stats</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container footer-container">
            <div>
                &copy; @(DateTime.Now.Year == 2024 ? "2024" : "2024 - " + DateTime.Now.Year.ToString()) Caleb Johnson
            </div>
            <div>
                <span class="footer-item"><i>Site icon by <a href="https://www.flaticon.com/authors/smalllikeart">smalllikeart</a></i></span>
                <a asp-controller="Home" asp-action="Contact" class="footer-item">Contact</a> 
                <a asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
             
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

PersonalWebsite/Views/Stories/Index.cshtml
@{
    ViewData["Title"] = "Short Stories";
}
@using PersonalWebsite.Models
@model List<Story>

<div>
    @foreach (Story story in Model)
    {
        <h3>@Html.ActionLink(story.Name, "ReadStory", "Stories", new { storyId = story.StoryId })</h3>
        <p>@story.Description</p>
    }
    <br />
</div>

PersonalWebsite/Views/Stories/ReadStory.cshtml
@{
    ViewData["Title"] = "Short Stories";
}
@using PersonalWebsite.Models
@model Story

@if (Model.StoryId > 0)
{
    <div class="text-center">
        <h1>@Model.Name</h1>
        <h3>@Model.Description</h3>
        <p><i>Written @(Model.DateWritten.ToString("MMMM")) @(Model.DateWritten.ToString("yyyy"))</i></p>
    </div>
    <div class="story-content">
        @Html.Raw(Model.Content)
    </div>
}
else
{
    <div class="text-center">
        <h2>No story with this ID found.</h2>
    </div>
}

PersonalWebsite/Views/Tabletop/Index.cshtml
@{
    ViewData["Title"] = "How did you get here?";
}

<div class="text-center">
    <h3>What are you doing here?</h3>    
</div>

PersonalWebsite/Views/Tabletop/KeyKiosk.cshtml
@{
    ViewData["Title"] = "DICE Lockup Kiosk";
}
@model KeyKioskViewModel

@section Styles {
    <style>
        body {
            background-color: #000000;
        }
    </style>
}

<img style="width: 15%; position:absolute; right: 100px; top: 100px" src="/img/KioskNote.png" alt="Hint Note" />

<div class="vertical-item-container-full">
    <img src="/img/DICE Logo.webp" alt="DICE Logo"/>

    <div class="text-center">
        <h3>@Model.Message</h3>
    </div>

    @using (Html.BeginForm("KeyKiosk", "Tabletop"))
    {
        <div class="vertical-item-container">
            <div>@Html.TextBoxFor(Model => Model.EnteredId)</div>
            <input type="submit" value="Submit" class="btn btn-dark" id="btnSubmit" />
        </div>
    }

    <p style="color: #000000">REMEMBER: We must acquire ALL Magatama before we can launch the invasion.</p>
</div>

PersonalWebsite/Views/Worldbuilding/Index.cshtml
@{
    ViewData["Title"] = "Worldbuilding";
}
@using PersonalWebsite.Models
@model List<World>

<div>
    @foreach (World world in Model)
    {
        <h3>@Html.ActionLink(world.Name, world.Identifier, "Worldbuilding")</h3>
        <p>@world.Description</p>
    }
    <br />
</div>

PersonalWebsite/Views/Worldbuilding/Jetsetter.cshtml
@{
    ViewData["Title"] = "World of Jetsetter";
}
@using PersonalWebsite.Models
@model List<Article>

<div>
    <h1>
        The World of Jet-setter
    </h1>
    <p>
        In the year 2345, humanity has fled from the climate change-ridden Earth and settled amongst the stars. They did so using the discovery of deep-sea algae which can teleport using magic, an energy which allows some species to bend the rules of physics.
    </p>
    <p>
        Most of the lore of this world was written as fictional Wikipedia articles or book excerpts, so those will be transcribed here.
    </p>
</div>
<br />
<div>
    @foreach (Article article in Model)
    {
        <p>@Html.ActionLink(article.Name, "ReadArticle", "Worldbuilding", new { articleId = article.ArticleId })</p>
    }
    <br />
</div>

PersonalWebsite/Views/Worldbuilding/ReadArticle.cshtml
@{
    ViewData["Title"] = "World of Jetsetter";
}
@using PersonalWebsite.Models
@model Article

@if (Model.ArticleId > 0)
{
    <div class="text-center">
        <h1>@Model.Name</h1>
    </div>
    <br />
    <div class="story-content">
        @Html.Raw(Model.Content)
    </div>
}
else
{
    <div class="text-center">
        <h2>No article with this ID found.</h2>
    </div>
}